services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: pokemon_db
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/postgre/utils/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - skn_net

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: pokemon_backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5433/${POSTGRES_DB}
    ports:
      - "8080:8000"
    depends_on:
      - postgres
    networks:
      - skn_net
    working_dir: /app
    volumes:
      - ./backend:/app
      - ./requirements.txt:/requirements.txt
    command: >
      sh -c "pip install --no-cache-dir -r /requirements.txt &&
             uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: pokemon_frontend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      BACKEND_URL: http://backend:8000
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - skn_net
    volumes:
      - ./frontend:/app
      - ./requirements.txt:/requirements.txt
    command: >
      sh -c "pip install --no-cache-dir -r /requirements.txt &&
             streamlit run app.py --server.port 8501 --server.address 0.0.0.0 --server.fileWatcherType poll"

networks:
  skn_net:
    driver: bridge

volumes:
  postgres_data:
